name: Copy CSV File to Repository

on:
  push:
    branches:
      - main

jobs:
  copy_csv:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
        
    - name: Generate CSV file
      run: python Sample_Py_create_csv_file.py  # Replace with the command to generate the CSV file

    - name: Move CSV file to repository
      run: |
        ls -l
        mkdir -p csv_files
        mv *.csv csv_files/
        ls -l csv_files/

    - name: Commit and push changes
      run: |
        cd $GITHUB_WORKSPACE || exit 1
        if [[ $(git status --porcelain) ]]; then
          git config --local user.email "gv.reddy77@gmail.com"
          git config --local user.name "omega1477"
          git add csv_files/*.csv
          git commit -m "Add generated CSV file"
          git push origin main
        else
          echo "No changes to commit."
        fi

    - name: Lock Pull Request
      uses: sudo-bot/action-pull-request-lock@v1.1.0
      with:
        github-token: ${{ secrets.ACCESS_TOKEN }}
        number: ${{ github.event.pull_request.number }}
        lock-reason: resolved
